### PR TITLE
HW3

### PR DESCRIPTION
**Pull request by nickytagoe**

### CODE REVIEW

**Review by showmic09 — CHANGES_REQUESTED** [review]
Please address the comments @nickytagoe

**Comment by showmic09** [comment]
@nickytagoe you didn't delete the Assignment file under HW3 folder in this PR..

**Comment by nickytagoe** [comment]
please I have deleted it

**Comment by nickytagoe** [comment]
@showmic09 please I have deleted it

**Review by showmic09 — APPROVED** [review]
LGTM..

**Pull request merged**
