### PR TITLE
Create debug.md

### LINKED ISSUE #32: Fix the error on the transfer_input_files line

### PR DESCRIPTION
**Pull request by aliinasrabadi**
closes #32
Hi, I did the changes and editted the file.

### CODE REVIEW

**Comment by showmic09** [comment]
@aliinasrabadi, please add closes #_issue_number_ in a comment. please replace the _issue_number_ with the one that's assigned to you. You can find the issue number in the issues page. The Lecture-9 video has instructions about it in the very beginning.

**Comment by aliinasrabadi** [comment]
Dear Dr. Islam,

I did it, I was looking for assigning you as a reviewer. My issue number
was 32. I put it in the comment. If there is any problem with that,
please let me know to edit it. Thank you very much once again.

Best regards,
Ali

**Comment by showmic09** [comment]
@aliinasrabadi, In the same thread you don't need to assign me twice as a reviewer

**Comment by aliinasrabadi** [comment]
Dear Dr. Islam,

Thank you so much for your kind help and support. That is most kind of you.
I think it is done now. Thank you very much once again.

Best regards,
Ali

**Pull request merged**
